version: "3.8"

services:
  frontend:
    build:
      context: https://github.com/jpthurman/example-voting-vote:main
      dockerfile: Dockerfile
    command: sh -c "yarn && yarn start"

volumes:
  frontend:

continuous previews:
  deploy_preview_when_pull_request_is_opened: true
  delete_prevew_when_pull_request_is_closed: true
  share_to_github: true
  delete_preview_after: 4hr
  
ingress:
  service: frontend
  port: 3000
